### ISSUE TITLE
Support for google news native RSS

### ISSUE THREAD

**Issue by RyuunosukeDS3** [VolkovLabs/volkovlabs-rss-datasource#51]
For some wreason when i try to use google news rss it errors out.

Google news rss link:

https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREZ0ZHpFU0FtVnVLQUFQAQ?hl=en-US&gl=US&ceid=US%3Aen

error:

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/31015675/c68b1dfb-e2dc-4c9d-b917-a72b8e857c17)

**Comment by mikhail-vl** [comment]
@RyuunosukeDS3 Data Source requires the correct URL. Otherwise, it had to redirect resources, which triggers CORS restrictions.

![Screenshot 2023-06-21 at 08 53 54](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/47795110/ff795c40-1037-4370-8531-5973c62608a0)

You can see error details in the Browser Console.

![Screenshot 2023-06-21 at 08 54 57](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/47795110/95d5e219-25e2-4a11-b2d2-f1cfc699f70f)

Let us know if there is anything else.

**Comment by mikhail-vl** [comment]
@RyuunosukeDS3 RSS Data Source uses CORS Proxy in the Go backend, but when the URL is incorrect it gives CORS errors, which is expected.

  Just fix the error, updating escaped characters like in the screenshot and it should work.

**Comment by RyuunosukeDS3** [comment]
Aaah just saw the screen shot right now. Apologies! Will try it later then! Thanks for the info.
