### ISSUE TITLE
RSS error with azure status page RSS

### ISSUE THREAD

**Issue by dpalat** [VolkovLabs/volkovlabs-rss-datasource#54]
Hello! I can't read the rss form from the Azure status page, 
examples: https://azure.status.microsoft/en-us/status/feed/
https://azure.status.microsoft/status/feed/

maybe is a little think that you can change for the next version of this plugins in order to provide support with this kind of RSS Type.

I see CORS errors in the console browser but I think is not about CORS error 
![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/2325020/363a0c65-d8ce-4133-95a4-0a15d7496b96)

Thanks a lot!

**Comment by mikhail-vl** [comment]
@dpalat The News is the native Grafana panel. It does not support CORS feeds, because runs from the browser.

  We created RSS/Atom data source, which use proxy backend and does not have this limitation.
  Here is the documentation to get Started: https://volkovlabs.io/plugins/volkovlabs-rss-datasource/.
  Let us know if there is anything else.

**Comment by dpalat** [comment]
thanks :) my bad, I think the "news" is the plugin, but is about a new datasource, sorry and thank for support :)

**Comment by mikhail-vl** [comment]
@dpalat No worries, let us know if it works for you.
