### ISSUE TITLE
Not able to use Jenkins RSS due to authentication issue

### ISSUE THREAD

**Issue by sudoharish** [VolkovLabs/volkovlabs-rss-datasource#55]
as an example i tried this also http://user:password@jenkins.example.com/job/multi/rssAll

**Comment by mikhail-vl** [comment]
@sudoharish I have not tried the data source with authentication-required feeds. I have to test it.

  I guess the Grafana proxy backend requires providing authentication separately as secure JSON parameters instead of specifying them in the data source.

  I will take a look, meanwhile, you can try Infinity Data Source, which should be able to retrieve the feed.

**Comment by mikhail-vl** [comment]
We don't plan to add authentication to the RSS/Atom Data Source.
  Please use Infinity Data Source to access resources with authentication.
